### ISSUE TITLE
Log file created in non-existent log subdirectory 

### ISSUE THREAD

**Issue by danieldreier** [danascheider/canto#82]
Following a basic installation (install mysql, bundle install, etc), running rackup results in an error due to a missing directory:

```shell
danieldreier@daniels-mbp~/personal/canto$ rackup config.ru
/Users/danieldreier/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/logger.rb:600:in `initialize': No such file or directory @ rb_sysopen - /Users/danieldreier/personal/canto/log/db.log (
Errno::ENOENT)
```

It looks like there's a hardcoded log path in `config/settings.rb` on line 36:
```
db_loggers = [Logger.new(File.expand_path('../../log/db.log', __FILE__))]
```

Creating a "log" directory solves the problem in an immediate sense, but still requires that the log live in the code directory. I can work around that by symlinking log to `/var/log/canto` or similar but it would be more convenient to have a configurable log directory in an ini/yaml/xml/whatever configuration file.

**Comment by danascheider** [comment]
Created `config.yml` - should be fixed as of ed0e912641510031dff456e819c617d3fc2e0d60
